{% set name = "vault" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/hashicorp/{{ name }}  # [not win]
    url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    fn: {{ name }}-{{ version }}.tar.gz  # [not win]
    sha256: 5f7edef332b622d6b9897bf252e27251178e7f0f4745cfb27e2179e72d5a769b  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    fn: {{ name }}-{{ version }}.zip  # [win]
    sha256: 40625092265076ff20925a29fde13e9bd64a5dfca9abfe7d73a59b5f8f2d24b9  # [win64]

build:
  number: 1000

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - git  # [not win]
    - make  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
