{% set name = "vault" %}
{% set version = "0.9.5" %}

{% set sha256 = "2ceaa347257e21e4020293ce68e2026f00655ef7c381f84dda1a487009c8d90f" %}
{% set sha256_win32 = "1d22b82bb2ec2378061f6b45e6280bd3915754acead7ff912644508249d40a2a" %}
{% set sha256_win64 = "50a25a66836e45e890dcf197d510e0e6ff44fc6e1e41a34746e6fd184a9be6df" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: {{ sha256_win32 }}  # [win32]
  sha256: {{ sha256_win64 }}  # [win64]

build:
  number: 0

requirements:
  build:
    - go 1.10.*  # [not win]
    - git  # [not win]
    - make  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
