{% set name = "vault" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/hashicorp/{{ name }}  # [not win]
    url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    fn: {{ name }}-{{ version }}.tar.gz  # [not win]
    sha256: 7f5e6f87c1f9505f814d45cdaa2ef2cc6a49129fa51f71498875d47b0a4a2ef2  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    fn: {{ name }}-{{ version }}.zip  # [win]
    sha256: aa38b5a393858c9f72596881a0cd223715659e69a6ea4f5394fcc7c8e7fe3e78  # [win64]

build:
  number: 1000

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - git  # [not win]
    - make  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
