{% set version = "0.8.3" %}

package:
  name: vault
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_windows_386.zip  # [win32]
  fn: vault-{{ version }}.zip
  sha256: 43c211d0a2ced793a25ac157cc4f3e2160ea9aa57f8d91f805a51e78a5b0b538  # [osx]
  sha256: 01d29a91498437027728f382c6e6551e64b380f506e276577c673e998f5aed70  # [linux32]
  sha256: a3b687904cd1151e7c7b1a3d016c93177b33f4f9ce5254e1d4f060fca2ac2626  # [linux64]
  sha256: 1fb1d837a085e1feceae00753b496735db746674ad3c55938f50545d1607dc32  # [win32]
  sha256: 9cdef19513bc0e8d51a2764505bbcda3b5caa3db83f4fbe2c64cd2d0d6e5779c  # [win64]

build:
  number: 0

test:
  commands:
    - vault -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
