{% set name = "vault" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/hashicorp/{{ name }}  # [not win]
    url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    fn: {{ name }}-{{ version }}.tar.gz  # [not win]
    sha256: d26da3b145036ce78083adc61f57fc02d0aae85de554ffcf8789e7861953ddaf  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    fn: {{ name }}-{{ version }}.zip  # [win]
    sha256: 9628ea3208be00f162ac1329da1a2a7dbdb4a5e57bece5c5379d872c04df8533  # [win64]

build:
  number: 1000

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - git  # [not win]
    - make  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
