{% set version = "0.7.1" %}

package:
  name: vault
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_windows_386.zip  # [win32]
  fn: vault-{{ version }}.zip
  sha256: 9060e4e64b76b566b8ea4f5c76df605292c2aa184b6ec6c1e1fa1afe343e371d  # [osx]
  sha256: 761783a5a66dddbc74fd87606760379ad992cc4649611ec4ec4fb51c865676eb  # [linux32]
  sha256: a576fe2c717ea4b5968477757196ff5308dbded4f5083c91d9e2ea824d2d6fdc  # [linux64]
  sha256: efdd4c064af9fe7ec5508ef07075a3c68192cd6a9ed3c68b201bbf9d5cd02112  # [win32]
  sha256: 27f6f476650d61b1435bd8f24eca97ecabcb789e1e8a0f8388d59ac4f90517ad  # [win64]

build:
  number: 0

test:
  commands:
    - vault -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
