{% set name = "vault" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: fb5d96e682a48bfd421b13cdfffd710da0238dbded1988aab822dd5aae75b4c4

build:
  number: 0
  script:
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - vault -v

about:
  home: https://www.vaultproject.io
  license: MPL-2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html
  dev_url: https://github.com/hashicorp/vault.git

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - adbeda
    - mariusvniekerk
    - oblute
    - rluria14
