{% set import_path = "github.com/hashicorp/vault" %}
{% set name = import_path.split('/')[-1] %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/{{ import_path }}
    git_url: https://{{ import_path }}
    git_tag: v{{version}}

build:
  number: 1000
  script:
    - pushd src/{{ import_path }}
    - go get -d -v .

    - export GOBIN=${PREFIX}/bin  # [unix]
    - set GOBIN=${LIBRARY_BIN}  # [win]

    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
