travis:
  secure:
    BINSTAR_TOKEN: ah/SgrO9NbwgnMEiejm2+ncXCbnruvCEDYcu0FcI9VJLpdiOw8ixwoq/Bn8HxLQsCDykrMF2X5/gwBPXEPiFtzXx3IyTeAieEoWtdsmlzDgaQqcZO8hQebx7a3jnFDguzgWMbokDRG7xKYF3DHfe9y+fbJ5jgFrZ0HM1xzU1+z2/UzhB4r8HqlcaegXylC+3LP7/MGYXwZeOaxxpKG5Jn1vClE38H0Ny5inu+Fd7kdf2I8BFZ4Ezo2Dqn0PMHHqqkxKBUMrU2lb1C5yluOKP/PabcbHxToy2Tfe4dtamkBlJn2o90HtAgklV24xwNQpjBcJQvvQ+9LYmpQy2F4zVK0BsPNLzarpMPOKa40AY3biXEZxgyATlIIVgmxh6meldxddEIT2ZjWtolc8Oas+MubI5yTwPPddB+HzOkcIi4YVinFnkKOHsU15r9WalkjGJess85KePbhxNIbW/8xqZLMOV5Wx0rgX3tWjge3CZoz6wmBqEkdvakEl34Wuh/NpAiXOsK9dO4V9HkmV3s2B62/ItWwsAZH7JyoIGZ1M8zxwcNocQ5idAqw7OUaHsrbqIZt7wPx4eFYcTIo+z5muHBUOKC9TvCR5yzJjsoqKLReawFH7WCH9gcD7rj1dEHgvXnXKlls/CIuH9rXzegzVJRw7F3M9soNqTLD1TSM+yND8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
