travis:
  secure:
    BINSTAR_TOKEN: QHVWasU4WBqmo0aZAoZ2lwF47poSjW0FiG/aC45ALv17Sx9mNKtvHb52VDlsRJaoHdaTsiZh9oeVEODazkiHp+o2Z+vT5avLI8v6cXo824WAvfPGu131kq4Pif7JTP1l/0AopYNMJuev2x3Qc1X4yUmRVzt8u3P/tPw9ufZ79DM314DaJwIUFd9IExCo5rq/LvBb9YFfOBg3QCpteoRhj9HFoU6ZhBG2pdNKHYkZ8yxAyXTHE66sux4NFg60HJ7KYWejWxOUQEpFUdUXxYEqmHO6Y/JaDHQynzQwa5tZZJPtOf5sJxg9WczCcgCBLuQQhZJ0OsvgjX0Epb3rSpXvGxjwne4qJ/yEQYXSi5lCIOkaXiFawikCxry6x2g6PpzwEScexF9QN0dP3QjNhsE3XktfAv3G8B2lmydFCikSQIwBNY6A5kY+UkkteREXe2SWEEfwyk3Dk/Ps8kDQfi6aTqqiUghFuLyhL/XwhscCQxAxhA6SweAmuv0dgkyJsM0YnS1JVgSeA++/V/OumVl5qGgd6cx5KoTDrsyfudZ9BFpGaojYHChcOekLUkSQcZPjNeGzSWVwyavofpBYJ6O21GDpUqaM1b7ubCJxda89lLOXNorEhQo1IlzkzHXwluj5gO0JQ4lGbzXhmafA0aED6EKBEAkmR5gX1NycWzHRAx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
