travis:
  secure:
    BINSTAR_TOKEN: mAcct2jjyVrPqtXvde4tw7bJrjdDYU57C04HJYVtavxVk7Pf7lGIx8ubn+V53i6UFkz4WiuBBh0Fkd2Q80hK7sV9IwhcbXti4Ssy+kqa8SSo9/QVTUq7U88tX8fkbb0BNDqceX+puuK8ZCKsTRMl6b5PMcTaX/xZXVSrabZwlUs04yD/26UfCZ4g5JtpwAqAwIFtYDQSYQr5+RX+ikjwkS6KrQ0FauKP2cK/5bwV4dppJP9MwuX/flF2m14p+6sd52tZWS48rhOOO3SijTF2KKSokLpOVJquix2eubw7STBmM1KLjp5XjuTzrvpA64AbPQkxNGxHj9wqYKSP0fXtfU8ZCxV4kobWDi5Y7ipjs8UyoVIErpEu6k6OHMk904XbAHcjefOFqfEIU3ytxY5lJG+k/ffSHw/VOTN0q+KLMLEyGQ+i1hjflYPIUmOm8f8ksTCP0gq4T6NzJiQDjCAFyZi9ObG9L4Sqx8DE3+AAV4zvFYXOW6KNQ6C2UPsZ173vKAZOH/cxglL8Q9hf+XkVkpbD2PPIbL5Mqg0cr3rb5KueGZOK6pVyUg2lI9h3D7eE5v2/07uXxQYPrgEaJsynp8yATYSjVXEU3HVOVGweJ3DyH2fcAHzGeZmYMGpBEiIO3w3iaqDhbew356z9fhXIcb8kqi9mTjqNavLzqmWDDoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
